import React, { useEffect, useMemo, useState } from "react";
import { WorkspaceHeader } from "./WorkspaceHeader";

interface Holding { id?: number; name: string; asset_type: string; symbol: string; units: number | null; invested_amount: number; current_value: number; platform: string; goal: string; notes: string; updated_at?: string; }
const API = window.location.hostname === "localhost" ? "http://localhost:8000" : window.location.origin;
const money = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value || 0);
const TYPES = ["Indian Equity", "Mutual Fund", "Fixed Deposit", "PPF / EPF", "NPS", "Gold", "Bonds", "US Equity", "Other"];
const COLORS = ["#176f57", "#d09645", "#51799a", "#7c6da8", "#a45d54", "#529482", "#9a8054", "#65707f", "#8b988c"];
const emptyHolding: Holding = { name: "", asset_type: "Indian Equity", symbol: "", units: null, invested_amount: 0, current_value: 0, platform: "", goal: "", notes: "" };

export function InvestmentPortfolio({ onLogout }: { onLogout?: () => void }) {
  const [holdings, setHoldings] = useState<Holding[]>([]);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");
  const [editing, setEditing] = useState<Holding | null>(null);
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All assets");
  const load = async () => { setLoading(true); try { const response = await fetch(`${API}/api/portfolio`); if (!response.ok) throw new Error(); setHoldings(await response.json()); } catch { setMessage("Could not load your portfolio. Please check the connection."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);

  const totals = useMemo(() => { const invested = holdings.reduce((s, h) => s + Number(h.invested_amount), 0); const current = holdings.reduce((s, h) => s + Number(h.current_value), 0); const gain = current - invested; return { invested, current, gain, returns: invested ? gain / invested * 100 : 0 }; }, [holdings]);
  const allocations = useMemo(() => TYPES.map((type, index) => ({ type, color: COLORS[index], value: holdings.filter(h => h.asset_type === type).reduce((s, h) => s + Number(h.current_value), 0) })).filter(i => i.value > 0).sort((a, b) => b.value - a.value), [holdings]);
  const filtered = holdings.filter(h => (filter === "All assets" || h.asset_type === filter) && `${h.name} ${h.symbol} ${h.platform}`.toLowerCase().includes(search.toLowerCase()));
  let turn = 0; const gradient = allocations.length ? `conic-gradient(${allocations.map(a => { const start = turn; turn += a.value / totals.current * 100; return `${a.color} ${start}% ${turn}%`; }).join(",")})` : "#e4eae7";
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!editing) return; const method = editing.id ? "PUT" : "POST"; const url = editing.id ? `${API}/api/portfolio/${editing.id}` : `${API}/api/portfolio`; try { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); if (!response.ok) throw new Error(); setEditing(null); setMessage("Holding saved securely."); await load(); } catch { setMessage("Holding could not be saved. Please review the values."); } };
  const remove = async (holding: Holding) => { if (!holding.id || !confirm(`Remove ${holding.name} from your portfolio?`)) return; const response = await fetch(`${API}/api/portfolio/${holding.id}`, { method: "DELETE" }); if (response.ok) { setMessage("Holding removed."); load(); } };

  return <div className="money-workspace portfolio-workspace">
    <WorkspaceHeader section="Portfolio" onLogout={onLogout} />
    <main className="money-content">
      <section className="money-heading"><div><span className="suite-eyebrow">YOUR COMPLETE WEALTH VIEW</span><h1>One portfolio. Every asset.</h1><p>Track investments across platforms and understand what you own, how it is growing, and where it is allocated.</p></div><button className="primary-action heading-action" onClick={() => setEditing({ ...emptyHolding })}><i className="fas fa-plus" /> Add investment</button></section>
      {message && <div className={`money-notice ${message.includes("saved") || message.includes("removed") ? "success" : ""}`}>{message}</div>}
      <section className="portfolio-hero"><div><span>Current portfolio value</span><strong>{money(totals.current)}</strong><p className={totals.gain >= 0 ? "positive" : "negative"}><i className={`fas fa-arrow-${totals.gain >= 0 ? "up" : "down"}`} /> {money(Math.abs(totals.gain))} ({Math.abs(totals.returns).toFixed(2)}%) overall</p></div><div className="wealth-motif" aria-hidden="true"><i className="fas fa-seedling" /><span /><span /><span /></div></section>
      <section className="money-stats portfolio-stats"><article><span>Amount invested</span><strong>{money(totals.invested)}</strong><small>Your total cost</small></article><article><span>Absolute gain</span><strong className={totals.gain >= 0 ? "positive" : "negative"}>{money(totals.gain)}</strong><small>Current less invested</small></article><article><span>Holdings</span><strong>{holdings.length}</strong><small>Across {allocations.length} asset classes</small></article><article><span>Top allocation</span><strong>{allocations[0]?.type || "—"}</strong><small>{allocations[0] && totals.current ? `${(allocations[0].value / totals.current * 100).toFixed(0)}% of portfolio` : "Add holdings to begin"}</small></article></section>
      <div className="portfolio-layout">
        <section className="money-panel holdings-panel"><div className="panel-title"><div><h2>Your holdings</h2><p>Values entered by you</p></div></div><div className="holding-tools"><label><i className="fas fa-search" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search investments" /></label><select value={filter} onChange={e => setFilter(e.target.value)}><option>All assets</option>{TYPES.map(type => <option key={type}>{type}</option>)}</select></div>
          {loading ? <div className="money-loading"><span className="money-spinner" />Loading portfolio…</div> : filtered.length === 0 ? <div className="portfolio-empty"><span><i className="fas fa-chart-pie" /></span><h3>{holdings.length ? "No matching holdings" : "Build your complete wealth view"}</h3><p>{holdings.length ? "Try a different search or asset filter." : "Add shares, mutual funds, FDs, retirement accounts, gold and more."}</p>{!holdings.length && <button className="primary-action" onClick={() => setEditing({ ...emptyHolding })}>Add your first investment</button>}</div> : <div className="holdings-table"><div className="holding-head"><span>Investment</span><span>Invested</span><span>Current</span><span>Returns</span><span></span></div>{filtered.map((h, index) => { const gain = h.current_value - h.invested_amount; const returns = h.invested_amount ? gain / h.invested_amount * 100 : 0; return <div className="holding-row" key={h.id}><div className="holding-name"><span style={{ background: COLORS[TYPES.indexOf(h.asset_type)] || COLORS[8] }}>{h.name.charAt(0).toUpperCase()}</span><div><strong>{h.name}</strong><small>{h.asset_type}{h.symbol && ` • ${h.symbol}`}{h.platform && ` • ${h.platform}`}</small></div></div><span>{money(h.invested_amount)}</span><strong>{money(h.current_value)}</strong><span className={gain >= 0 ? "positive" : "negative"}>{gain >= 0 ? "+" : ""}{money(gain)}<small>{returns.toFixed(2)}%</small></span><div className="holding-actions"><button onClick={() => setEditing({ ...h })} aria-label={`Edit ${h.name}`}><i className="fas fa-pen" /></button><button onClick={() => remove(h)} aria-label={`Delete ${h.name}`}><i className="fas fa-trash" /></button></div></div>; })}</div>}
        </section>
        <aside className="money-panel allocation-panel"><span className="panel-kicker">ASSET ALLOCATION</span><h2>How your money is spread</h2><div className="allocation-donut" style={{ background: gradient }}><div><strong>{allocations.length}</strong><span>asset classes</span></div></div><div className="allocation-list">{allocations.map(item => <div key={item.type}><i style={{ background: item.color }} /><span>{item.type}</span><strong>{totals.current ? (item.value / totals.current * 100).toFixed(1) : 0}%</strong><small>{money(item.value)}</small></div>)}</div>{!allocations.length && <p className="allocation-empty">Your allocation will appear here after you add an investment.</p>}<div className="portfolio-disclaimer"><i className="fas fa-circle-info" /><span>This is a personal tracker, not investment advice. Current values are entered by you.</span></div></aside>
      </div>
    </main>
    {editing && <div className="money-modal" role="dialog" aria-modal="true" aria-labelledby="holding-title"><form className="money-modal-card holding-modal" onSubmit={save}><div className="modal-heading"><div><span>PORTFOLIO HOLDING</span><h2 id="holding-title">{editing.id ? "Edit investment" : "Add an investment"}</h2></div><button type="button" onClick={() => setEditing(null)} aria-label="Close"><i className="fas fa-times" /></button></div><div className="form-grid"><label className="wide">Investment name<input required autoFocus value={editing.name} onChange={e => setEditing({ ...editing, name: e.target.value })} placeholder="e.g. Nifty 50 Index Fund" /></label><label>Asset class<select value={editing.asset_type} onChange={e => setEditing({ ...editing, asset_type: e.target.value })}>{TYPES.map(type => <option key={type}>{type}</option>)}</select></label><label>Symbol / folio<input value={editing.symbol} onChange={e => setEditing({ ...editing, symbol: e.target.value })} placeholder="Optional" /></label><label>Amount invested (₹)<input required type="number" min="0" step="0.01" value={editing.invested_amount || ""} onChange={e => setEditing({ ...editing, invested_amount: Number(e.target.value) })} /></label><label>Current value (₹)<input required type="number" min="0" step="0.01" value={editing.current_value || ""} onChange={e => setEditing({ ...editing, current_value: Number(e.target.value) })} /></label><label>Units<input type="number" min="0" step="0.0001" value={editing.units ?? ""} onChange={e => setEditing({ ...editing, units: e.target.value ? Number(e.target.value) : null })} placeholder="Optional" /></label><label>Platform<input value={editing.platform} onChange={e => setEditing({ ...editing, platform: e.target.value })} placeholder="Zerodha, Groww, bank…" /></label><label className="wide">Goal<input value={editing.goal} onChange={e => setEditing({ ...editing, goal: e.target.value })} placeholder="Retirement, home, emergency fund…" /></label></div><div className="modal-actions"><button type="button" className="secondary-action" onClick={() => setEditing(null)}>Cancel</button><button className="primary-action" type="submit">Save investment</button></div></form></div>}
  </div>;
}
